import Foundation

// MARK: - Game Map HTML Content

/// Provides the HTML content for the WebView game map.
/// The HTML file is copied to a known location during build, or embedded at compile time.
enum GameMapHTML {
    /// The full HTML content for the pixel-art office game map.
    /// Loaded from the Resources directory at runtime.
    static var content: String {
        // Try loading from SPM resource bundle first (generated by .copy("Resources"))
        if let url = Bundle.module.url(forResource: "gamemap", withExtension: "html", subdirectory: "Resources"),
           let html = try? String(contentsOf: url, encoding: .utf8) {
            return html
        }

        // Try app main bundle
        if let url = Bundle.main.url(forResource: "gamemap", withExtension: "html"),
           let html = try? String(contentsOf: url, encoding: .utf8) {
            return html
        }

        // Try loading from the source tree (development mode)
        let possiblePaths = [
            // Relative to executable
            URL(fileURLWithPath: CommandLine.arguments[0])
                .deletingLastPathComponent()
                .appendingPathComponent("Resources/gamemap.html"),
            // Source tree location
            URL(fileURLWithPath: #filePath)
                .deletingLastPathComponent()
                .deletingLastPathComponent()
                .deletingLastPathComponent()
                .appendingPathComponent("Resources/gamemap.html"),
        ]

        for path in possiblePaths {
            if let html = try? String(contentsOf: path, encoding: .utf8) {
                return html
            }
        }

        // Fallback: try home directory
        let home = FileManager.default.homeDirectoryForCurrentUser
        let fallbackPaths = [
            home.appendingPathComponent(".pixel-agents/gamemap.html"),
            URL(fileURLWithPath: "/tmp/pixel-agents-macos-work/macos/Sources/PixelAgents/Resources/gamemap.html"),
        ]

        for path in fallbackPaths {
            if let html = try? String(contentsOf: path, encoding: .utf8) {
                return html
            }
        }

        // Last resort: minimal error HTML
        return """
        <!DOCTYPE html>
        <html><body style="background:#1a1a2e;color:#F97316;font-family:monospace;display:flex;align-items:center;justify-content:center;height:100vh">
        <div style="text-align:center">
        <h2>Game Map Not Found</h2>
        <p>Could not load gamemap.html from any known location.</p>
        </div>
        </body></html>
        """
    }
}
